#ifndef SDK_CONFIG_H
#define SDK_CONFIG_H

#define BLE_ADVERTISING_ENABLED 1
#define FSTORAGE_ENABLED 1

/* FSTORAGE values from template file in sdk */
#define FS_QUEUE_SIZE 4 /**< the size of the internal queue */
#define FS_MAX_WRITE_SIZE_WORDS 256 /**< Maximum number of words to be written to flash in a single operation. */
#define FS_OP_MAX_RETRIES 3 /**< Number attempts to execute an operation if the SoftDevice fails */

#define APP_TIMER_ENABLED 1

#define CLOCK_ENABLED 1
#define CLOCK_CONFIG_XTAL_FREQ 255
/* 0 for RC, 1 for XTAL, 2 for synth */
#define CLOCK_CONFIG_LF_SRC 1
#define CLOCK_CONFIG_IRQ_PRIORITY 3

/* For SDK consistency */
#define NRF_CLOCK_LFCLKSRC {.source        = NRF_CLOCK_LF_SRC_XTAL, \
	.rc_ctiv       = 0, \
	.rc_temp_ctiv  = 0, \
	.xtal_accuracy = NRF_CLOCK_LF_XTAL_ACCURACY_20_PPM}

#define PEER_MANAGER_ENABLED 1

/* Values copied from template */
#define FDS_ENABLED 1
#define FDS_OP_QUEUE_SIZE 4
#define FDS_CHUNK_QUEUE_SIZE 8
#define FDS_MAX_USERS 8
#define FDS_VIRTUAL_PAGES 3
#define FDS_VIRTUAL_PAGE_SIZE 256

#define GPIOTE_ENABLED 1
#define GPIOTE_CONFIG_NUM_OF_LOW_POWER_EVENTS 4
#define GPIOTE_CONFIG_IRQ_PRIORITY 3
#define GPIOTE_CONFIG_LOG_ENABLED 0
#define GPIOTE_CONFIG_LOG_LEVEL 3
#define GPIOTE_CONFIG_INFO_COLOR 0
#define GPIOTE_CONFIG_DEBUG_COLOR 0

#define UART_ENABLED 1
#define UART_DEFAULT_CONFIG_HWFC 0
#define UART_DEFAULT_CONFIG_PARITY 0
#define UART_DEFAULT_CONFIG_BAUDRATE 30924800
#define UART_DEFAULT_CONFIG_IRQ_PRIORITY 3
#define UART_EASY_DMA_SUPPORT 1
#define UART_LEGACY_SUPPORT 1
#define UART0_ENABLED 1
#define UART0_CONFIG_USE_EASY_DMA 1

#define NRF_LOG_ENABLED 1
#define NRF_LOG_DEFAULT_LEVEL 4
#define NRF_LOG_DEFERRED 1
#define NRF_LOG_DEFERRED_BUFSIZE 256
#define NRF_LOG_USES_COLORS 0
#define NRF_LOG_USES_TIMESTAMP 0
#define NRF_LOG_TIMESTAMP_DIGITS 8

#define NRF_LOG_BACKEND_UART_INSTANCE 0

/* BLE400 pinout */
#define NRF_LOG_BACKEND_SERIAL_USES_UART 1
#define NRF_LOG_BACKEND_SERIAL_UART_TX_PIN 9
#define NRF_LOG_BACKEND_SERIAL_UART_RX_PIN 11
#define NRF_LOG_BACKEND_SERIAL_UART_CTS_PIN 10
#define NRF_LOG_BACKEND_SERIAL_UART_RTS_PIN 8
#define NRF_LOG_BACKEND_MAX_STRING_LENGTH 256
/* 115200 Baud */
#define NRF_LOG_BACKEND_SERIAL_UART_BAUDRATE 30924800
#define NRF_LOG_BACKEND_SERIAL_UART_FLOW_CONTROL 1


#endif
